/**:
  ros__parameters:
    feature_extract_enable: false
    point_filter_num: 3
    max_iteration: 5
    filter_size_surf: 0.4
    filter_size_map: 0.4
    cube_side_length: 200.0
    runtime_pos_log_enable: false
    map_file_path: "./test.pcd"

    common:
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      time_sync_en: false
      time_offset_lidar_to_imu: -0.010985

    preprocess:
      lidar_type: 1
      scan_line: 4
      blind: 0.35
      timestamp_unit: 3
      scan_rate: 10

    mapping:
      # acc_cov: 0.03
      acc_cov: 0.001 #0.001
      # gyr_cov: 0.003
      gyr_cov: 0.00000123 #0.00000123
      b_acc_cov: 0.00001 #0.00001
      b_gyr_cov: 0.0000001 #0.0000001
      fov_degree: 360.0
      det_range: 30.0
      extrinsic_est_en: false
      extrinsic_T: [ 0.000106, -0.014620, -0.011374 ]
      extrinsic_R: [ 0.999999, -0.001275, -0.001104,
                     0.001274,  0.999999, -0.001062,
                     0.001105,  0.001061,  0.999999 ]

    publish:
      path_en: true
      effect_map_en: false
      map_en: true
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: false

    pcd_save:
      pcd_save_en: false
      interval: 1
