amcl:
  ros__parameters:
    use_map_topic: true
    map_topic: "/Laser_map"  # Fast-LIO2's map topic
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "/livox/lidar"  # Your LIDAR topic
    use_sim_time: false

controller_server:
  ros__parameters:
    odom_topic: "/odom"
    base_frame_id: "base_link"
    cmd_vel_topic: "/cmd_vel"
    use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false

local_costmap:
  local_costmap:
    ros__parameters:
      footprint: "[[0.16, 0.13], [0.16, -0.13], [-0.16, -0.13], [-0.16, 0.13]]"
      global_frame: "odom"
      robot_base_frame: "base_link"
      use_sim_time: false
      update_frequency: 5.0
      publish_frequency: 2.0
      static_layer:
        map_subscribe_transient_local: true
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: /livox/lidar
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"

global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[0.16, 0.13], [0.16, -0.13], [-0.16, -0.13], [-0.16, 0.13]]"
      global_frame: "map"
      robot_base_frame: "base_link"
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0
      static_layer:
        map_subscribe_transient_local: true
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: /livox/lidar
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"

bt_navigator:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false 