#!/usr/bin/env python3
"""
Odometry Tilt Corrector - Transforms LiDAR frame odometry to Robot Body frame.

The LiDAR is mounted tilted relative to the robot body. This node transforms
Fast-LIO2 odometry from the tilted LiDAR frame to the robot's initial body
frame (ground-aligned, with robot's initial heading).

The tilt correction can be loaded from a calibration file (generated by
tilt_calibration.py) or use a fixed pitch angle as fallback.

Output frame properties:
- Origin: Robot's initial position (at startup)
- Orientation: Robot's initial heading (yaw=0 at startup)
- XY plane: Parallel to ground (level with robot body)
- X axis: Robot's initial forward direction
- Z axis: Perpendicular to ground (up)
"""
import rclpy
from rclpy.node import Node
from rclpy.qos import (
    qos_profile_sensor_data,
    QoSProfile,
    DurabilityPolicy,
    ReliabilityPolicy,
    HistoryPolicy,
)
from nav_msgs.msg import Odometry
from sensor_msgs.msg import Imu
from std_msgs.msg import Bool
import numpy as np
import math
import os
from datetime import datetime


# Default LiDAR mount angle (degrees) - used as fallback if no calibration file
LIDAR_PITCH_DEG = 15.0


class OdomTiltCorrector(Node):
    def __init__(self):
        super().__init__('odom_tilt_corrector')

        # Parameters
        self.declare_parameter('odometry_topic', '/Odometry')
        self.declare_parameter('corrected_odometry_topic', '/Odometry_tilt_corrected_diff')
        self.declare_parameter('save_directory', '')  # Session folder path for saving transformation
        self.declare_parameter('calibration_file', '')  # Path to tilt_correction_matrices.npz
        self.declare_parameter('lidar_pitch_deg', LIDAR_PITCH_DEG)  # Last-resort tilt angle (degrees)

        # Gravity-based live leveling parameters. The IMU accelerometer measures
        # true "up" while the robot is stationary; averaging it over a quiet
        # window yields a full pitch+roll levelling rotation, independent of the
        # (pitch-only) stored calibration and of the start-surface slope.
        self.declare_parameter('imu_topic', '/livox/imu')
        self.declare_parameter('use_gravity_init', True)
        self.declare_parameter('grav_window_sec', 2.0)       # contiguous stationary window
        self.declare_parameter('grav_max_gyro', 0.05)        # rad/s; above -> disturbance
        self.declare_parameter('grav_max_accel_dev', 0.05)   # |a| deviation from running mean (IMU accel units)
        self.declare_parameter('grav_max_accel_std', 0.03)   # per-axis std over window (IMU accel units)
        self.declare_parameter('grav_min_samples', 100)
        self.declare_parameter('grav_timeout_sec', 8.0)      # fall back to stored calibration after this
        self.declare_parameter('grav_disagree_warn_deg', 2.0)

        self.odom_topic = str(self.get_parameter('odometry_topic').value)
        self.output_topic = str(self.get_parameter('corrected_odometry_topic').value)
        self.save_directory = str(self.get_parameter('save_directory').value)
        self.calibration_file = str(self.get_parameter('calibration_file').value)
        self.lidar_pitch_deg = float(self.get_parameter('lidar_pitch_deg').value)
        self.lidar_pitch_rad = math.radians(self.lidar_pitch_deg)

        self.imu_topic = str(self.get_parameter('imu_topic').value)
        self.use_gravity_init = bool(self.get_parameter('use_gravity_init').value)
        self.grav_window_sec = float(self.get_parameter('grav_window_sec').value)
        self.grav_max_gyro = float(self.get_parameter('grav_max_gyro').value)
        self.grav_max_accel_dev = float(self.get_parameter('grav_max_accel_dev').value)
        self.grav_max_accel_std = float(self.get_parameter('grav_max_accel_std').value)
        self.grav_min_samples = int(self.get_parameter('grav_min_samples').value)
        self.grav_timeout_sec = float(self.get_parameter('grav_timeout_sec').value)
        self.grav_disagree_warn_deg = float(self.get_parameter('grav_disagree_warn_deg').value)

        # Fixed coordinate flip; MUST match tilt_calibration.py's R_flip so the
        # live gravity path and the stored fallback share one frame convention.
        self.R_flip = np.array([[-1.0, 0.0, 0.0],
                                [0.0, 1.0, 0.0],
                                [0.0, 0.0, -1.0]], dtype=float)

        # State
        self.pose_initialized = False
        self.origin_set = False
        self.using_calibration = False
        self.leveling_latched = False
        self.leveling_source = 'none'

        # Stored calibration matrix used as the fallback (None if unavailable).
        self.R_file = self._load_file_r_map()

        # Live tilt correction (LiDAR body -> levelled robot). Set on latch.
        self.R_lidar_to_robot = np.eye(3, dtype=float)

        # Full transformation from LiDAR world frame to robot's initial frame
        # Combines: pitch/roll levelling + initial yaw removal
        self.R_init = np.eye(3, dtype=float)

        # Origin in LiDAR world frame (first odometry position)
        self.p0_lidar = np.zeros(3, dtype=float)

        # Initial LiDAR orientation (to remove initial yaw)
        self.R0_lidar = np.eye(3, dtype=float)

        # Gravity accumulation state (running sums -> O(1) per-sample update)
        self._grav_sum = np.zeros(3, dtype=float)
        self._grav_sumsq = np.zeros(3, dtype=float)
        self._grav_sum_mag = 0.0
        self._grav_count = 0
        self._grav_win_start = None
        self._grav_reset_logged = False
        self._start_sec = self._now_sec()

        # Publisher for corrected odometry
        self.odom_pub = self.create_publisher(Odometry, self.output_topic, 10)

        # Latched leveling-ready signal. The drive controllers gate ODrive
        # arming on this so motors only arm once levelling is fixed.
        latched_qos = QoSProfile(
            depth=1,
            history=HistoryPolicy.KEEP_LAST,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        self.leveling_ready_pub = self.create_publisher(Bool, '/leveling_ready', latched_qos)

        # Odometry subscription
        self.odom_sub = self.create_subscription(
            Odometry, self.odom_topic, self.odom_callback, qos_profile_sensor_data
        )

        self.get_logger().info('Odom tilt corrector (LiDAR->Robot frame) started')
        self.get_logger().info(f'  Input: "{self.odom_topic}" -> Output: "{self.output_topic}"')

        if self.use_gravity_init:
            self.imu_sub = self.create_subscription(
                Imu, self.imu_topic, self.imu_callback, qos_profile_sensor_data
            )
            self._grav_timeout_timer = self.create_timer(0.5, self._check_grav_timeout)
            self.get_logger().info(
                f'  Gravity-init leveling ENABLED (imu="{self.imu_topic}", '
                f'window={self.grav_window_sec:.1f}s, timeout={self.grav_timeout_sec:.1f}s)')
        else:
            self.get_logger().info('  Gravity-init leveling DISABLED; using stored calibration')
            self._latch_fallback()

    def _load_file_r_map(self):
        """
        Load the stored tilt correction (R_map) used as the gravity fallback.

        Returns:
            3x3 rotation matrix, or None if no usable calibration file.
        """
        if self.calibration_file and os.path.exists(self.calibration_file):
            try:
                data = np.load(self.calibration_file)
                if 'R_map' in data:
                    self.using_calibration = True
                    if 'pitch_deg' in data:
                        pitch = float(data['pitch_deg'])
                        roll = float(data.get('roll_deg', 0.0))
                        self.get_logger().info(
                            f'Loaded calibration: pitch={pitch:.2f} deg, roll={roll:.2f} deg')
                    return np.array(data['R_map'], dtype=float)
                self.get_logger().warn(
                    f'Calibration file missing R_map key: {self.calibration_file}')
            except Exception as e:
                self.get_logger().warn(f'Failed to load calibration file: {e}')
        elif self.calibration_file:
            self.get_logger().warn(f'Calibration file not found: {self.calibration_file}')
        return None

    # ---------------- Math utilities ----------------
    @staticmethod
    def _build_pitch_rotation(pitch_rad):
        """Build rotation matrix for pitch (rotation around Y-axis)."""
        cp = np.cos(pitch_rad)
        sp = np.sin(pitch_rad)
        return np.array([[cp,  0.0, sp],
                         [0.0, 1.0, 0.0],
                         [-sp, 0.0, cp]], dtype=float)

    @staticmethod
    def _build_yaw_rotation(yaw_rad):
        """Build rotation matrix for yaw (rotation around Z-axis)."""
        cy = np.cos(yaw_rad)
        sy = np.sin(yaw_rad)
        return np.array([[cy, -sy, 0.0],
                         [sy,  cy, 0.0],
                         [0.0, 0.0, 1.0]], dtype=float)

    @staticmethod
    def _extract_yaw_from_matrix(R):
        """Extract yaw angle from rotation matrix (ZYX Euler convention)."""
        return np.arctan2(R[1, 0], R[0, 0])

    @staticmethod
    def quat_to_matrix(q):
        """Convert quaternion (x, y, z, w) to rotation matrix."""
        x, y, z, w = q
        xx = x * x; yy = y * y; zz = z * z
        xy = x * y; xz = x * z; yz = y * z
        wx = w * x; wy = w * y; wz = w * z
        R = np.array([
            [1.0 - 2.0 * (yy + zz),     2.0 * (xy - wz),         2.0 * (xz + wy)],
            [    2.0 * (xy + wz),   1.0 - 2.0 * (xx + zz),       2.0 * (yz - wx)],
            [    2.0 * (xz - wy),       2.0 * (yz + wx),     1.0 - 2.0 * (xx + yy)]
        ], dtype=float)
        return R

    @staticmethod
    def matrix_to_quat(R):
        """Convert rotation matrix to quaternion (x, y, z, w)."""
        m00, m01, m02 = float(R[0,0]), float(R[0,1]), float(R[0,2])
        m10, m11, m12 = float(R[1,0]), float(R[1,1]), float(R[1,2])
        m20, m21, m22 = float(R[2,0]), float(R[2,1]), float(R[2,2])
        tr = m00 + m11 + m22
        if tr > 0.0:
            S = math.sqrt(tr + 1.0) * 2.0
            w = 0.25 * S
            x = (m21 - m12) / S
            y = (m02 - m20) / S
            z = (m10 - m01) / S
        elif (m00 > m11) and (m00 > m22):
            S = math.sqrt(1.0 + m00 - m11 - m22) * 2.0
            w = (m21 - m12) / S
            x = 0.25 * S
            y = (m01 + m10) / S
            z = (m02 + m20) / S
        elif m11 > m22:
            S = math.sqrt(1.0 + m11 - m00 - m22) * 2.0
            w = (m02 - m20) / S
            x = (m01 + m10) / S
            y = 0.25 * S
            z = (m12 + m21) / S
        else:
            S = math.sqrt(1.0 + m22 - m00 - m11) * 2.0
            w = (m10 - m01) / S
            x = (m02 + m20) / S
            y = (m12 + m21) / S
            z = 0.25 * S
        return (x, y, z, w)

    @staticmethod
    def quaternion_to_yaw(qx, qy, qz, qw):
        """Extract yaw angle from quaternion."""
        siny_cosp = 2.0 * (qw * qz + qx * qy)
        cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
        return math.atan2(siny_cosp, cosy_cosp)

    @staticmethod
    def quaternion_to_rpy(qx, qy, qz, qw):
        """Convert quaternion to roll, pitch, yaw."""
        sinr_cosp = 2.0 * (qw * qx + qy * qz)
        cosr_cosp = 1.0 - 2.0 * (qx * qx + qy * qy)
        roll = math.atan2(sinr_cosp, cosr_cosp)
        sinp = 2.0 * (qw * qy - qz * qx)
        if abs(sinp) >= 1.0:
            pitch = math.copysign(math.pi / 2.0, sinp)
        else:
            pitch = math.asin(sinp)
        siny_cosp = 2.0 * (qw * qz + qx * qy)
        cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
        yaw = math.atan2(siny_cosp, cosy_cosp)
        return roll, pitch, yaw

    # ---------------- Gravity-based leveling ----------------
    def _now_sec(self):
        return self.get_clock().now().nanoseconds * 1e-9

    @staticmethod
    def _align_vectors(u, target):
        """Minimal rotation matrix mapping unit vector u onto unit vector target (Rodrigues)."""
        u = np.asarray(u, dtype=float)
        u = u / (np.linalg.norm(u) + 1e-12)
        t = np.asarray(target, dtype=float)
        t = t / (np.linalg.norm(t) + 1e-12)
        v = np.cross(u, t)
        s = float(np.linalg.norm(v))
        c = float(np.dot(u, t))
        if s < 1e-9:
            if c > 0.0:
                return np.eye(3, dtype=float)
            # Antiparallel: 180 deg about any axis perpendicular to u
            axis = np.cross(u, np.array([1.0, 0.0, 0.0]))
            if np.linalg.norm(axis) < 1e-6:
                axis = np.cross(u, np.array([0.0, 1.0, 0.0]))
            axis = axis / (np.linalg.norm(axis) + 1e-12)
            vx = np.array([[0.0, -axis[2], axis[1]],
                           [axis[2], 0.0, -axis[0]],
                           [-axis[1], axis[0], 0.0]], dtype=float)
            return np.eye(3, dtype=float) + 2.0 * (vx @ vx)
        vx = np.array([[0.0, -v[2], v[1]],
                       [v[2], 0.0, -v[0]],
                       [-v[1], v[0], 0.0]], dtype=float)
        return np.eye(3, dtype=float) + vx + vx @ vx * ((1.0 - c) / (s * s))

    @staticmethod
    def _tilt_between(v, ref):
        """Angle (deg) between two vectors."""
        v = np.asarray(v, dtype=float)
        v = v / (np.linalg.norm(v) + 1e-12)
        ref = np.asarray(ref, dtype=float)
        ref = ref / (np.linalg.norm(ref) + 1e-12)
        return math.degrees(math.acos(max(-1.0, min(1.0, float(np.dot(v, ref))))))

    def _reset_grav_window(self):
        self._grav_sum[:] = 0.0
        self._grav_sumsq[:] = 0.0
        self._grav_sum_mag = 0.0
        self._grav_count = 0
        self._grav_win_start = None

    def imu_callback(self, msg: Imu):
        if self.leveling_latched:
            return
        a = np.array([msg.linear_acceleration.x,
                      msg.linear_acceleration.y,
                      msg.linear_acceleration.z], dtype=float)
        w = np.array([msg.angular_velocity.x,
                      msg.angular_velocity.y,
                      msg.angular_velocity.z], dtype=float)
        amag = float(np.linalg.norm(a))
        gyro_norm = float(np.linalg.norm(w))

        # Per-sample stationary gate. Any trip resets the contiguous window so
        # only an uninterrupted quiet stretch is averaged.
        disturbed = gyro_norm > self.grav_max_gyro
        if not disturbed and self._grav_count > 0:
            mean_mag = self._grav_sum_mag / self._grav_count
            if abs(amag - mean_mag) > self.grav_max_accel_dev:
                disturbed = True
        if disturbed:
            if self._grav_count > 0 and not self._grav_reset_logged:
                self.get_logger().warn(
                    'Motion detected during leveling window; restarting stationary capture.')
                self._grav_reset_logged = True
            self._reset_grav_window()
            return

        # Accept sample
        if self._grav_count == 0:
            self._grav_win_start = self._now_sec()
        self._grav_sum += a
        self._grav_sumsq += a * a
        self._grav_sum_mag += amag
        self._grav_count += 1

        # Latch once we have a long-enough, quiet-enough contiguous window.
        if (self._grav_win_start is not None
                and (self._now_sec() - self._grav_win_start) >= self.grav_window_sec
                and self._grav_count >= self.grav_min_samples):
            n = self._grav_count
            mean = self._grav_sum / n
            var = np.maximum(self._grav_sumsq / n - mean * mean, 0.0)
            std = np.sqrt(var)
            if float(np.max(std)) <= self.grav_max_accel_std:
                self._latch_gravity(mean)
            # else: aggregate too noisy; keep collecting until quiet or timeout

    def _check_grav_timeout(self):
        if self.leveling_latched:
            self._grav_timeout_timer.cancel()
            return
        if (self._now_sec() - self._start_sec) >= self.grav_timeout_sec:
            self.get_logger().warn(
                f'Gravity leveling did not settle within {self.grav_timeout_sec:.1f}s; '
                f'falling back to stored calibration.')
            self._latch_fallback()
            self._grav_timeout_timer.cancel()

    def _latch_gravity(self, a_avg):
        a_body = np.asarray(a_avg, dtype=float)
        norm = float(np.linalg.norm(a_body))
        if norm < 1e-6:
            self.get_logger().warn('Degenerate gravity sample; falling back to stored calibration.')
            self._latch_fallback()
            return
        a_body = a_body / norm
        # Full pitch+roll levelling: measured "up" -> +Z, then fixed coordinate flip.
        R_align = self._align_vectors(a_body, np.array([0.0, 0.0, 1.0]))
        self.R_lidar_to_robot = self.R_flip @ R_align

        # Field diagnostic: stored R_map should also send gravity to [0,0,-1];
        # the leftover angle is the residual tilt the stored calibration bakes in.
        if self.R_file is not None:
            resid = self._tilt_between(self.R_file @ a_body, np.array([0.0, 0.0, -1.0]))
            if resid > self.grav_disagree_warn_deg:
                self.get_logger().warn(
                    f'Gravity vs stored R_map disagree by {resid:.2f} deg '
                    f'(stored calibration would leave this residual tilt).')

        tilt = self._tilt_between(a_body, np.array([0.0, 0.0, 1.0]))
        pitch = math.degrees(math.atan2(a_body[0], a_body[2]))
        roll = math.degrees(math.atan2(a_body[1], a_body[2]))
        self.get_logger().info(
            f'Gravity leveling latched (n={self._grav_count}): corrected mount tilt='
            f'{tilt:.2f} deg (pitch={pitch:.2f}, roll={roll:.2f})')
        self._finish_latch('gravity')

    def _latch_fallback(self):
        if self.R_file is not None:
            self.R_lidar_to_robot = self.R_file
            src = 'file_R_map'
        else:
            self.R_lidar_to_robot = self._build_pitch_rotation(-self.lidar_pitch_rad)
            src = f'fixed_pitch_{self.lidar_pitch_deg:.1f}deg'
        self._finish_latch(src)

    def _finish_latch(self, source):
        if self.leveling_latched:
            return
        self.leveling_latched = True
        self.leveling_source = source
        msg = Bool()
        msg.data = True
        self.leveling_ready_pub.publish(msg)
        self.get_logger().info(f'Leveling ready (source={source}); motor arming unblocked.')

    # ---------------- Odom processing ----------------
    def odom_callback(self, msg: Odometry):
        """
        Transform Fast-LIO2 odometry from LiDAR frame to robot's initial body frame.
        
        The transformation consists of:
        1. Pitch correction: Fixed 15° rotation to account for LiDAR mount tilt
        2. Origin shift: Robot starts at (0,0,0) in output frame
        3. Initial yaw removal: Robot starts with yaw=0 (facing +X direction)
        
        Output frame is the robot's body frame at t=0:
        - XY plane parallel to ground
        - X axis = robot's initial forward direction
        - Z axis = up (perpendicular to ground)
        """
        # Hold off until the levelling rotation is latched (gravity or fallback).
        if not self.leveling_latched:
            return

        # Extract raw pose from Fast-LIO2 (in LiDAR world frame)
        raw_pos = np.array([
            float(msg.pose.pose.position.x),
            float(msg.pose.pose.position.y),
            float(msg.pose.pose.position.z),
        ], dtype=float)
        raw_q = (
            float(msg.pose.pose.orientation.x),
            float(msg.pose.pose.orientation.y),
            float(msg.pose.pose.orientation.z),
            float(msg.pose.pose.orientation.w),
        )
        R_lidar_world_to_body = self.quat_to_matrix(raw_q)

        # ============ FIRST ODOMETRY: Compute transformation ============
        if not self.origin_set:
            # Store initial LiDAR pose for origin and yaw removal
            self.p0_lidar = raw_pos.copy()
            self.R0_lidar = R_lidar_world_to_body.copy()
            
            # Compute initial yaw in the pitch-corrected frame
            # First apply pitch correction to initial orientation
            R0_robot = self.R_lidar_to_robot @ self.R0_lidar
            initial_yaw = self._extract_yaw_from_matrix(R0_robot)
            
            # Create yaw removal matrix (rotate by -initial_yaw around Z)
            R_yaw_remove = self._build_yaw_rotation(-initial_yaw)
            
            # Combine into final transformation:
            # R_init = R_yaw_remove @ R_lidar_to_robot
            # This transforms: LiDAR world frame → Robot's initial body frame
            self.R_init = R_yaw_remove @ self.R_lidar_to_robot
            
            self.origin_set = True
            
            self.get_logger().info(
                f'✓ Transformation initialized:')
            self.get_logger().info(
                f'  Leveling source: {self.leveling_source}')
            self.get_logger().info(
                f'  Origin (LiDAR frame): [{self.p0_lidar[0]:.3f}, {self.p0_lidar[1]:.3f}, {self.p0_lidar[2]:.3f}]')
            self.get_logger().info(
                f'  Initial yaw removed: {math.degrees(initial_yaw):.2f}°')
            self.get_logger().info(
                f'  Robot starts at (0, 0, 0) with yaw=0°')
            
            # Save transformation details
            # self._save_transformation(initial_yaw)

        # ============ TRANSFORM POSITION ============
        # p_robot = R_init @ (p_lidar - p0_lidar)
        p_robot = self.R_init @ (raw_pos - self.p0_lidar)
        
        # ============ TRANSFORM ORIENTATION ============
        # R_robot = R_init @ R_lidar_world_to_body
        # This gives orientation relative to robot's initial frame
        R_robot = self.R_init @ R_lidar_world_to_body
        q_robot = self.matrix_to_quat(R_robot)
        
        # Extract state for logging
        current_x = float(p_robot[0])
        current_y = float(p_robot[1])
        current_yaw = self.quaternion_to_yaw(q_robot[0], q_robot[1], q_robot[2], q_robot[3])
        
        # ============ TRANSFORM VELOCITIES ============
        # Velocities are in LiDAR body frame, transform to robot body frame
        # Only need pitch correction (not yaw removal, since velocity is body-relative)
        raw_vel = np.array([
            float(msg.twist.twist.linear.x),
            float(msg.twist.twist.linear.y),
            float(msg.twist.twist.linear.z)
        ], dtype=float)
        
        # Transform velocity from LiDAR body frame to robot body frame
        vel_robot = self.R_lidar_to_robot @ raw_vel
        
        # Transform angular velocity
        raw_omega = np.array([
            float(msg.twist.twist.angular.x),
            float(msg.twist.twist.angular.y),
            float(msg.twist.twist.angular.z)
        ], dtype=float)
        omega_robot = self.R_lidar_to_robot @ raw_omega
        
        # ============ LOG FIRST POSE ============
        if not self.pose_initialized:
            self.pose_initialized = True
            r, p, y = self.quaternion_to_rpy(q_robot[0], q_robot[1], q_robot[2], q_robot[3])
            self.get_logger().info(
                f'✓ First pose in robot frame: '
                f'pos=[{current_x:.3f}, {current_y:.3f}, {p_robot[2]:.3f}] '
                f'rpy=[{math.degrees(r):.1f}°, {math.degrees(p):.1f}°, {math.degrees(y):.1f}°]')

        # ============ PUBLISH CORRECTED ODOMETRY ============
        odom_corr = Odometry()
        odom_corr.header.stamp = msg.header.stamp
        odom_corr.header.frame_id = 'robot_init'  # Robot's initial frame
        odom_corr.child_frame_id = 'robot_body'
        
        # Position in robot's initial frame
        odom_corr.pose.pose.position.x = current_x
        odom_corr.pose.pose.position.y = current_y
        odom_corr.pose.pose.position.z = float(p_robot[2])
        
        # Orientation relative to robot's initial frame
        odom_corr.pose.pose.orientation.x = q_robot[0]
        odom_corr.pose.pose.orientation.y = q_robot[1]
        odom_corr.pose.pose.orientation.z = q_robot[2]
        odom_corr.pose.pose.orientation.w = q_robot[3]
        
        # Velocity in robot body frame (pitch-corrected, level with ground)
        odom_corr.twist.twist.linear.x = float(vel_robot[0])   # Forward
        odom_corr.twist.twist.linear.y = float(vel_robot[1])   # Lateral
        odom_corr.twist.twist.linear.z = float(vel_robot[2])   # Vertical
        
        # Angular velocity in robot body frame
        odom_corr.twist.twist.angular.x = float(omega_robot[0])
        odom_corr.twist.twist.angular.y = float(omega_robot[1])
        odom_corr.twist.twist.angular.z = float(omega_robot[2])
        
        self.odom_pub.publish(odom_corr)

    # ---------------- Save transformation ----------------
    def _save_transformation(self, initial_yaw):
        """Save the transformation details to files using old naming convention."""
        if not self.save_directory or not os.path.exists(self.save_directory):
            self.get_logger().warn(f'Save directory not set or does not exist: {self.save_directory}')
            return
        
        try:
            timestamp = datetime.now()
            timestamp_str = timestamp.strftime("%Y%m%d_%H%M%S")
            
            # Save rotation matrices as numpy binary (old naming: tilt_correction_matrices_*)
            np_file = os.path.join(self.save_directory, f'tilt_correction_matrices_{timestamp_str}.npz')
            np.savez(
                np_file,
                R_map=self.R_init,              # Old name for full transformation matrix
                p0_world=self.p0_lidar,         # Old name for origin offset
                R_lidar_to_robot=self.R_lidar_to_robot,
                initial_yaw=initial_yaw,
                lidar_pitch_deg=self.lidar_pitch_deg,
                timestamp=timestamp_str
            )
            
            # Save human-readable CSV
            csv_file = os.path.join(self.save_directory, f'tilt_correction_matrices_{timestamp_str}.csv')
            with open(csv_file, 'w') as f:
                f.write('# LiDAR to Robot Frame Transformation\n')
                f.write(f'# Generated: {timestamp.strftime("%Y-%m-%d %H:%M:%S")}\n')
                f.write('#\n')
                f.write(f'# LiDAR mount pitch: {self.lidar_pitch_deg:.1f} degrees (fixed)\n')
                f.write(f'# Initial yaw removed: {math.degrees(initial_yaw):.2f} degrees\n')
                f.write('#\n')
                f.write('# Transformation formula:\n')
                f.write('#   p_robot = R_map @ (p_raw - p0_world)\n')
                f.write('#   R_robot = R_map @ R_raw\n')
                f.write('#   v_robot = R_lidar_to_robot @ v_raw\n')
                f.write('#\n')
                f.write('# Origin (first odometry position)\n')
                f.write(f'p0_world_x,{self.p0_lidar[0]:.6f}\n')
                f.write(f'p0_world_y,{self.p0_lidar[1]:.6f}\n')
                f.write(f'p0_world_z,{self.p0_lidar[2]:.6f}\n')
                f.write('#\n')
                f.write('# R_lidar_to_robot (pitch correction matrix)\n')
                for i in range(3):
                    f.write(f'{self.R_lidar_to_robot[i,0]:.8f},{self.R_lidar_to_robot[i,1]:.8f},{self.R_lidar_to_robot[i,2]:.8f}\n')
                f.write('#\n')
                f.write('# R_map (full transformation matrix)\n')
                for i in range(3):
                    f.write(f'{self.R_init[i,0]:.8f},{self.R_init[i,1]:.8f},{self.R_init[i,2]:.8f}\n')
            
            self.get_logger().info(f'✓ Transformation saved to:\n  - {np_file}\n  - {csv_file}')
            
        except Exception as e:
            self.get_logger().error(f'Failed to save transformation: {e}')


def main(args=None):
    rclpy.init(args=args)
    node = OdomTiltCorrector()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
