#!/usr/bin/env python3
"""
Odometry Tilt Corrector - Transforms LiDAR frame odometry to Robot Body frame.

The LiDAR is mounted tilted relative to the robot body. This node transforms
Fast-LIO2 odometry from the tilted LiDAR frame to the robot's initial body
frame (ground-aligned, with robot's initial heading).

The tilt correction can be loaded from a calibration file (generated by
tilt_calibration.py) or use a fixed pitch angle as fallback.

Output frame properties:
- Origin: Robot's initial position (at startup)
- Orientation: Robot's initial heading (yaw=0 at startup)
- XY plane: Parallel to ground (level with robot body)
- X axis: Robot's initial forward direction
- Z axis: Perpendicular to ground (up)
"""
import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data
from nav_msgs.msg import Odometry
import numpy as np
import math
import os
from datetime import datetime


# Default LiDAR mount angle (degrees) - used as fallback if no calibration file
LIDAR_PITCH_DEG = 15.0


class OdomTiltCorrector(Node):
    def __init__(self):
        super().__init__('odom_tilt_corrector')

        # Parameters
        self.declare_parameter('odometry_topic', '/Odometry')
        self.declare_parameter('corrected_odometry_topic', '/Odometry_tilt_corrected_diff')
        self.declare_parameter('save_directory', '')  # Session folder path for saving transformation
        self.declare_parameter('calibration_file', '')  # Path to tilt_correction_matrices.npz
        self.declare_parameter('lidar_pitch_deg', LIDAR_PITCH_DEG)  # Fallback tilt angle (degrees)

        self.odom_topic = str(self.get_parameter('odometry_topic').value)
        self.output_topic = str(self.get_parameter('corrected_odometry_topic').value)
        self.save_directory = str(self.get_parameter('save_directory').value)
        self.calibration_file = str(self.get_parameter('calibration_file').value)
        self.lidar_pitch_deg = float(self.get_parameter('lidar_pitch_deg').value)
        self.lidar_pitch_rad = math.radians(self.lidar_pitch_deg)

        # State
        self.pose_initialized = False
        self.origin_set = False
        self.using_calibration = False
        
        # Try to load calibration file, fall back to fixed pitch
        self.R_lidar_to_robot = self._load_or_compute_tilt_correction()
        
        # Full transformation from LiDAR world frame to robot's initial frame
        # Combines: pitch correction + initial yaw removal
        self.R_init = np.eye(3, dtype=float)
        
        # Origin in LiDAR world frame (first odometry position)
        self.p0_lidar = np.zeros(3, dtype=float)
        
        # Initial LiDAR orientation (to remove initial yaw)
        self.R0_lidar = np.eye(3, dtype=float)

        # Subscription
        self.odom_sub = self.create_subscription(
            Odometry, self.odom_topic, self.odom_callback, qos_profile_sensor_data
        )

        # Publisher
        self.odom_pub = self.create_publisher(Odometry, self.output_topic, 10)

        self.get_logger().info(
            f'Odom tilt corrector (LiDAR→Robot frame) started')
        self.get_logger().info(
            f'  Input: "{self.odom_topic}" → Output: "{self.output_topic}"')
        if self.using_calibration:
            self.get_logger().info(
                f'  Using calibration file: {self.calibration_file}')
        else:
            self.get_logger().info(
                f'  Using fixed pitch correction: {self.lidar_pitch_deg:.1f}°')

    def _load_or_compute_tilt_correction(self):
        """
        Load tilt correction from calibration file or compute from fixed pitch.
        
        Returns:
            R_lidar_to_robot: 3x3 rotation matrix for tilt correction
        """
        # Try to load calibration file
        if self.calibration_file and os.path.exists(self.calibration_file):
            try:
                data = np.load(self.calibration_file)
                if 'R_map' in data:
                    R_map = data['R_map']
                    self.using_calibration = True
                    
                    # Log calibration info if available
                    if 'pitch_deg' in data:
                        pitch = float(data['pitch_deg'])
                        roll = float(data.get('roll_deg', 0.0))
                        self.get_logger().info(
                            f'Loaded calibration: pitch={pitch:.2f}°, roll={roll:.2f}°')
                    
                    return R_map
                else:
                    self.get_logger().warn(
                        f'Calibration file missing R_map key: {self.calibration_file}')
            except Exception as e:
                self.get_logger().warn(
                    f'Failed to load calibration file: {e}')
        elif self.calibration_file:
            self.get_logger().warn(
                f'Calibration file not found: {self.calibration_file}')
        
        # Fall back to fixed pitch rotation
        self.using_calibration = False
        return self._build_pitch_rotation(-self.lidar_pitch_rad)

    # ---------------- Math utilities ----------------
    @staticmethod
    def _build_pitch_rotation(pitch_rad):
        """Build rotation matrix for pitch (rotation around Y-axis)."""
        cp = np.cos(pitch_rad)
        sp = np.sin(pitch_rad)
        return np.array([[cp,  0.0, sp],
                         [0.0, 1.0, 0.0],
                         [-sp, 0.0, cp]], dtype=float)

    @staticmethod
    def _build_yaw_rotation(yaw_rad):
        """Build rotation matrix for yaw (rotation around Z-axis)."""
        cy = np.cos(yaw_rad)
        sy = np.sin(yaw_rad)
        return np.array([[cy, -sy, 0.0],
                         [sy,  cy, 0.0],
                         [0.0, 0.0, 1.0]], dtype=float)

    @staticmethod
    def _extract_yaw_from_matrix(R):
        """Extract yaw angle from rotation matrix (ZYX Euler convention)."""
        return np.arctan2(R[1, 0], R[0, 0])

    @staticmethod
    def quat_to_matrix(q):
        """Convert quaternion (x, y, z, w) to rotation matrix."""
        x, y, z, w = q
        xx = x * x; yy = y * y; zz = z * z
        xy = x * y; xz = x * z; yz = y * z
        wx = w * x; wy = w * y; wz = w * z
        R = np.array([
            [1.0 - 2.0 * (yy + zz),     2.0 * (xy - wz),         2.0 * (xz + wy)],
            [    2.0 * (xy + wz),   1.0 - 2.0 * (xx + zz),       2.0 * (yz - wx)],
            [    2.0 * (xz - wy),       2.0 * (yz + wx),     1.0 - 2.0 * (xx + yy)]
        ], dtype=float)
        return R

    @staticmethod
    def matrix_to_quat(R):
        """Convert rotation matrix to quaternion (x, y, z, w)."""
        m00, m01, m02 = float(R[0,0]), float(R[0,1]), float(R[0,2])
        m10, m11, m12 = float(R[1,0]), float(R[1,1]), float(R[1,2])
        m20, m21, m22 = float(R[2,0]), float(R[2,1]), float(R[2,2])
        tr = m00 + m11 + m22
        if tr > 0.0:
            S = math.sqrt(tr + 1.0) * 2.0
            w = 0.25 * S
            x = (m21 - m12) / S
            y = (m02 - m20) / S
            z = (m10 - m01) / S
        elif (m00 > m11) and (m00 > m22):
            S = math.sqrt(1.0 + m00 - m11 - m22) * 2.0
            w = (m21 - m12) / S
            x = 0.25 * S
            y = (m01 + m10) / S
            z = (m02 + m20) / S
        elif m11 > m22:
            S = math.sqrt(1.0 + m11 - m00 - m22) * 2.0
            w = (m02 - m20) / S
            x = (m01 + m10) / S
            y = 0.25 * S
            z = (m12 + m21) / S
        else:
            S = math.sqrt(1.0 + m22 - m00 - m11) * 2.0
            w = (m10 - m01) / S
            x = (m02 + m20) / S
            y = (m12 + m21) / S
            z = 0.25 * S
        return (x, y, z, w)

    @staticmethod
    def quaternion_to_yaw(qx, qy, qz, qw):
        """Extract yaw angle from quaternion."""
        siny_cosp = 2.0 * (qw * qz + qx * qy)
        cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
        return math.atan2(siny_cosp, cosy_cosp)

    @staticmethod
    def quaternion_to_rpy(qx, qy, qz, qw):
        """Convert quaternion to roll, pitch, yaw."""
        sinr_cosp = 2.0 * (qw * qx + qy * qz)
        cosr_cosp = 1.0 - 2.0 * (qx * qx + qy * qy)
        roll = math.atan2(sinr_cosp, cosr_cosp)
        sinp = 2.0 * (qw * qy - qz * qx)
        if abs(sinp) >= 1.0:
            pitch = math.copysign(math.pi / 2.0, sinp)
        else:
            pitch = math.asin(sinp)
        siny_cosp = 2.0 * (qw * qz + qx * qy)
        cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
        yaw = math.atan2(siny_cosp, cosy_cosp)
        return roll, pitch, yaw

    # ---------------- Odom processing ----------------
    def odom_callback(self, msg: Odometry):
        """
        Transform Fast-LIO2 odometry from LiDAR frame to robot's initial body frame.
        
        The transformation consists of:
        1. Pitch correction: Fixed 15° rotation to account for LiDAR mount tilt
        2. Origin shift: Robot starts at (0,0,0) in output frame
        3. Initial yaw removal: Robot starts with yaw=0 (facing +X direction)
        
        Output frame is the robot's body frame at t=0:
        - XY plane parallel to ground
        - X axis = robot's initial forward direction
        - Z axis = up (perpendicular to ground)
        """
        # Extract raw pose from Fast-LIO2 (in LiDAR world frame)
        raw_pos = np.array([
            float(msg.pose.pose.position.x),
            float(msg.pose.pose.position.y),
            float(msg.pose.pose.position.z),
        ], dtype=float)
        raw_q = (
            float(msg.pose.pose.orientation.x),
            float(msg.pose.pose.orientation.y),
            float(msg.pose.pose.orientation.z),
            float(msg.pose.pose.orientation.w),
        )
        R_lidar_world_to_body = self.quat_to_matrix(raw_q)

        # ============ FIRST ODOMETRY: Compute transformation ============
        if not self.origin_set:
            # Store initial LiDAR pose for origin and yaw removal
            self.p0_lidar = raw_pos.copy()
            self.R0_lidar = R_lidar_world_to_body.copy()
            
            # Compute initial yaw in the pitch-corrected frame
            # First apply pitch correction to initial orientation
            R0_robot = self.R_lidar_to_robot @ self.R0_lidar
            initial_yaw = self._extract_yaw_from_matrix(R0_robot)
            
            # Create yaw removal matrix (rotate by -initial_yaw around Z)
            R_yaw_remove = self._build_yaw_rotation(-initial_yaw)
            
            # Combine into final transformation:
            # R_init = R_yaw_remove @ R_lidar_to_robot
            # This transforms: LiDAR world frame → Robot's initial body frame
            self.R_init = R_yaw_remove @ self.R_lidar_to_robot
            
            self.origin_set = True
            
            self.get_logger().info(
                f'✓ Transformation initialized:')
            self.get_logger().info(
                f'  Fixed pitch correction: {self.lidar_pitch_deg:.1f}°')
            self.get_logger().info(
                f'  Origin (LiDAR frame): [{self.p0_lidar[0]:.3f}, {self.p0_lidar[1]:.3f}, {self.p0_lidar[2]:.3f}]')
            self.get_logger().info(
                f'  Initial yaw removed: {math.degrees(initial_yaw):.2f}°')
            self.get_logger().info(
                f'  Robot starts at (0, 0, 0) with yaw=0°')
            
            # Save transformation details
            # self._save_transformation(initial_yaw)

        # ============ TRANSFORM POSITION ============
        # p_robot = R_init @ (p_lidar - p0_lidar)
        p_robot = self.R_init @ (raw_pos - self.p0_lidar)
        
        # ============ TRANSFORM ORIENTATION ============
        # R_robot = R_init @ R_lidar_world_to_body
        # This gives orientation relative to robot's initial frame
        R_robot = self.R_init @ R_lidar_world_to_body
        q_robot = self.matrix_to_quat(R_robot)
        
        # Extract state for logging
        current_x = float(p_robot[0])
        current_y = float(p_robot[1])
        current_yaw = self.quaternion_to_yaw(q_robot[0], q_robot[1], q_robot[2], q_robot[3])
        
        # ============ TRANSFORM VELOCITIES ============
        # Velocities are in LiDAR body frame, transform to robot body frame
        # Only need pitch correction (not yaw removal, since velocity is body-relative)
        raw_vel = np.array([
            float(msg.twist.twist.linear.x),
            float(msg.twist.twist.linear.y),
            float(msg.twist.twist.linear.z)
        ], dtype=float)
        
        # Transform velocity from LiDAR body frame to robot body frame
        vel_robot = self.R_lidar_to_robot @ raw_vel
        
        # Transform angular velocity
        raw_omega = np.array([
            float(msg.twist.twist.angular.x),
            float(msg.twist.twist.angular.y),
            float(msg.twist.twist.angular.z)
        ], dtype=float)
        omega_robot = self.R_lidar_to_robot @ raw_omega
        
        # ============ LOG FIRST POSE ============
        if not self.pose_initialized:
            self.pose_initialized = True
            r, p, y = self.quaternion_to_rpy(q_robot[0], q_robot[1], q_robot[2], q_robot[3])
            self.get_logger().info(
                f'✓ First pose in robot frame: '
                f'pos=[{current_x:.3f}, {current_y:.3f}, {p_robot[2]:.3f}] '
                f'rpy=[{math.degrees(r):.1f}°, {math.degrees(p):.1f}°, {math.degrees(y):.1f}°]')

        # ============ PUBLISH CORRECTED ODOMETRY ============
        odom_corr = Odometry()
        odom_corr.header.stamp = msg.header.stamp
        odom_corr.header.frame_id = 'robot_init'  # Robot's initial frame
        odom_corr.child_frame_id = 'robot_body'
        
        # Position in robot's initial frame
        odom_corr.pose.pose.position.x = current_x
        odom_corr.pose.pose.position.y = current_y
        odom_corr.pose.pose.position.z = float(p_robot[2])
        
        # Orientation relative to robot's initial frame
        odom_corr.pose.pose.orientation.x = q_robot[0]
        odom_corr.pose.pose.orientation.y = q_robot[1]
        odom_corr.pose.pose.orientation.z = q_robot[2]
        odom_corr.pose.pose.orientation.w = q_robot[3]
        
        # Velocity in robot body frame (pitch-corrected, level with ground)
        odom_corr.twist.twist.linear.x = float(vel_robot[0])   # Forward
        odom_corr.twist.twist.linear.y = float(vel_robot[1])   # Lateral
        odom_corr.twist.twist.linear.z = float(vel_robot[2])   # Vertical
        
        # Angular velocity in robot body frame
        odom_corr.twist.twist.angular.x = float(omega_robot[0])
        odom_corr.twist.twist.angular.y = float(omega_robot[1])
        odom_corr.twist.twist.angular.z = float(omega_robot[2])
        
        self.odom_pub.publish(odom_corr)

    # ---------------- Save transformation ----------------
    def _save_transformation(self, initial_yaw):
        """Save the transformation details to files using old naming convention."""
        if not self.save_directory or not os.path.exists(self.save_directory):
            self.get_logger().warn(f'Save directory not set or does not exist: {self.save_directory}')
            return
        
        try:
            timestamp = datetime.now()
            timestamp_str = timestamp.strftime("%Y%m%d_%H%M%S")
            
            # Save rotation matrices as numpy binary (old naming: tilt_correction_matrices_*)
            np_file = os.path.join(self.save_directory, f'tilt_correction_matrices_{timestamp_str}.npz')
            np.savez(
                np_file,
                R_map=self.R_init,              # Old name for full transformation matrix
                p0_world=self.p0_lidar,         # Old name for origin offset
                R_lidar_to_robot=self.R_lidar_to_robot,
                initial_yaw=initial_yaw,
                lidar_pitch_deg=self.lidar_pitch_deg,
                timestamp=timestamp_str
            )
            
            # Save human-readable CSV
            csv_file = os.path.join(self.save_directory, f'tilt_correction_matrices_{timestamp_str}.csv')
            with open(csv_file, 'w') as f:
                f.write('# LiDAR to Robot Frame Transformation\n')
                f.write(f'# Generated: {timestamp.strftime("%Y-%m-%d %H:%M:%S")}\n')
                f.write('#\n')
                f.write(f'# LiDAR mount pitch: {self.lidar_pitch_deg:.1f} degrees (fixed)\n')
                f.write(f'# Initial yaw removed: {math.degrees(initial_yaw):.2f} degrees\n')
                f.write('#\n')
                f.write('# Transformation formula:\n')
                f.write('#   p_robot = R_map @ (p_raw - p0_world)\n')
                f.write('#   R_robot = R_map @ R_raw\n')
                f.write('#   v_robot = R_lidar_to_robot @ v_raw\n')
                f.write('#\n')
                f.write('# Origin (first odometry position)\n')
                f.write(f'p0_world_x,{self.p0_lidar[0]:.6f}\n')
                f.write(f'p0_world_y,{self.p0_lidar[1]:.6f}\n')
                f.write(f'p0_world_z,{self.p0_lidar[2]:.6f}\n')
                f.write('#\n')
                f.write('# R_lidar_to_robot (pitch correction matrix)\n')
                for i in range(3):
                    f.write(f'{self.R_lidar_to_robot[i,0]:.8f},{self.R_lidar_to_robot[i,1]:.8f},{self.R_lidar_to_robot[i,2]:.8f}\n')
                f.write('#\n')
                f.write('# R_map (full transformation matrix)\n')
                for i in range(3):
                    f.write(f'{self.R_init[i,0]:.8f},{self.R_init[i,1]:.8f},{self.R_init[i,2]:.8f}\n')
            
            self.get_logger().info(f'✓ Transformation saved to:\n  - {np_file}\n  - {csv_file}')
            
        except Exception as e:
            self.get_logger().error(f'Failed to save transformation: {e}')


def main(args=None):
    rclpy.init(args=args)
    node = OdomTiltCorrector()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
