from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, TimerAction, OpaqueFunction
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
import os
import sys
import re
import glob
from pathlib import Path
from ament_index_python.packages import get_package_share_directory

# Import the folder setup script
# Get the package installation directory and add scripts to path
package_dir = Path(get_package_share_directory('pilot_control'))
# Try source directory first (for development)
source_script_dir = Path(__file__).parent.parent / 'scripts'
if source_script_dir.exists():
    sys.path.insert(0, str(source_script_dir))
else:
    # Fall back to installed location
    # Scripts are installed to lib/pilot_control, navigate there
    install_script_dir = package_dir.parent.parent / 'lib' / 'pilot_control'
    sys.path.insert(0, str(install_script_dir))

from setup_data_folders import setup_day_folder_only


# Tilt calibration directory (same as in tilt_calibration.py)
TILT_CALIBRATION_DIR = '/R_DATA/tilt_calibration'


def get_latest_calibration_file(calibration_dir=TILT_CALIBRATION_DIR):
    """
    Find the latest (highest index) tilt_correction_matrices_*.npz file.
    
    Args:
        calibration_dir: Directory containing calibration files
        
    Returns:
        Path to the latest calibration file, or empty string if none found
    """
    if not os.path.exists(calibration_dir):
        return ''
    
    pattern = os.path.join(calibration_dir, 'tilt_correction_matrices_*.npz')
    files = glob.glob(pattern)
    
    if not files:
        return ''
    
    # Extract indices and find the maximum
    max_index = -1
    latest_file = ''
    
    for f in files:
        basename = os.path.basename(f)
        match = re.match(r'tilt_correction_matrices_(\d+)\.npz', basename)
        if match:
            index = int(match.group(1))
            if index > max_index:
                max_index = index
                latest_file = f
    
    return latest_file

def generate_launch_description():
    # Find the latest tilt calibration file (generated by tilt_calibration.py)
    # Files are stored in /R_DATA/tilt_calibration/ with incrementing indices
    tilt_calibration_file = get_latest_calibration_file(TILT_CALIBRATION_DIR)
    
    if tilt_calibration_file:
        print(f"\n[Tilt Calibration] Using: {tilt_calibration_file}")
    else:
        print(f"\n[Tilt Calibration] WARNING: No calibration file found in {TILT_CALIBRATION_DIR}")
        print("[Tilt Calibration] Will use fixed 15° pitch fallback")
        print("[Tilt Calibration] Run 'ros2 run pilot_control tilt_calibration' to calibrate\n")
    
    # Start Zenoh bridge DDS daemon for Microhard communication
    # This must be running before ROS nodes launch for cross-network DDS communication
    zenoh_bridge = ExecuteProcess(
        cmd=['zenohd', '-c', os.path.expanduser('~/zenohd_robot.json5')],
        output='screen',
        name='zenoh_bridge_dds'
    )
    
    # Declare launch arguments
    declare_wheel_radius_arg = DeclareLaunchArgument(
        'wheel_radius',
        default_value='0.09',
        description='Radius of the wheels in meters.'
    )
    declare_wheel_base_arg = DeclareLaunchArgument(
        'wheel_base',
        default_value='0.355',
        description='Distance between the two wheels in meters.'
    )
    declare_can_interface_arg = DeclareLaunchArgument(
        'can_interface',
        default_value='can0',
        description='The CAN interface name.'
    )
    declare_can_bitrate_arg = DeclareLaunchArgument(
        'can_bitrate',
        default_value='250000',
        description='CAN interface bitrate.'
    )
    declare_velocity_multiplier_arg = DeclareLaunchArgument(
        'velocity_multiplier',
        default_value='1.0',
        description='A multiplier to tune the robot speed.'
    )
    declare_turn_speed_multiplier_arg = DeclareLaunchArgument(
        'turn_speed_multiplier',
        default_value='1.0',
        description='A multiplier to tune the robot turning speed.'
    )
    
    declare_base_data_directory_arg = DeclareLaunchArgument(
        'base_data_directory',
        default_value='/R_DATA',
        description='Base directory for all robot data collection.'
    )

    # Setup day folder only; section folders are created by data_collection_coordinator on /dc/start
    base_data_dir = '/R_DATA'
    folder_paths = setup_day_folder_only(base_data_dir)
    
    # Odometry Tilt Corrector - transforms LiDAR frame to robot body frame
    # Uses calibration file if available, otherwise falls back to fixed 15° pitch
    odom_tilt_corrector_node = Node(
        package='pilot_control',
        executable='odom_tilt_corrector',
        name='odom_tilt_corrector',
        output='screen',
        parameters=[{
            'odometry_topic': '/Odometry',
            'corrected_odometry_topic': '/Odometry_tilt_corrected_diff',
            'calibration_file': tilt_calibration_file,  # Load from config folder
            'lidar_pitch_deg': 15.0,  # Fallback if calibration file not found
            'save_directory': folder_paths['day_folder']  # Save transformation to day folder
        }]
    )
    
    print("\n" + "="*70)
    print("DATA COLLECTION SESSION SETUP")
    print("="*70)
    print(f"Day Folder:     {folder_paths['day_name']} ({folder_paths['day_folder']})")
    print("Section:        (created by data_collection_coordinator on /dc/start)")
    print("="*70 + "\n")
    # Unified Data Collector (Thermal + Dual Cameras + Odometry sync)
    unified_data_collector_node = Node(
        package='pilot_control',
        executable='unified_data_collector',
        name='unified_data_collector',
        output='screen',
        respawn=True,
        respawn_delay=2.0,
        parameters=[{
            # Odometry and thermal camera settings (using tilt-corrected odometry)
            'fastlio_odom_topic': '/Odometry_tilt_corrected_diff',
            'log_directory': '/R_DATA/unified_scans',  # Fallback until /dc/start sets section
            'visual_data_directory': '',  # Set by data_collection_coordinator on /dc/start
            'use_seekvision_mode': True,
            'save_color_png': True,
            'csv_flush_every_rows': 50,
            'log_frequency_hz': 10.0,
            
            # Camera device paths (See3CAM)
            'left_device': '/dev/v4l/by-id/usb-e-con_systems_See3CAM_24CUG_3728140416020900-video-index0',
            'right_device': '/dev/v4l/by-id/usb-e-con_systems_See3CAM_24CUG_0F12140416020900-video-index0',
            
            # Streaming settings
            'stream_host': '192.168.168.100', # TODO: change to 10.105.41.180 (R), 192.168.168.102 (R) / 10.105.41.193 (A), 192.168.168.100 (A)
            'stream_port': 5600, # TODO: change to 5602 (R) / 5600 (A)
            'stream_bitrate_kbps': 800,   # FPV optimized at 480x360@25fps
            'rtp_mtu': 1400,  # Larger MTU for efficiency
            
            # Video capture settings
            'use_mjpeg_pipeline': True,
            'cap_w': 1920,
            'cap_h': 1080,
            'cap_fps': 30,
            'raw_format': 'UYVY',
            'raw_w': 1280,
            'raw_h': 720,
            'raw_fps': 60,
        }]
    )

    # CAN interface setup command
    can_setup = ExecuteProcess(
        cmd=['sudo', 'ip', 'link', 'set', LaunchConfiguration('can_interface'), 
             'up', 'type', 'can', 'bitrate', LaunchConfiguration('can_bitrate')],
        output='screen'
    )

    # ODrive CAN nodes for motor control
    left_odrive_node = Node(
        package='odrive_can',
        executable='odrive_can_node',
        namespace='left',
        name='odrive_can_left',
        parameters=[{
            'node_id': 0,
            'interface': LaunchConfiguration('can_interface')
        }],
        output='screen'
    )

    right_odrive_node = Node(
        package='odrive_can',
        executable='odrive_can_node',
        namespace='right',
        name='odrive_can_right',
        parameters=[{
            'node_id': 1,
            'interface': LaunchConfiguration('can_interface')
        }],
        output='screen'
    )

    # ODrive CAN node for GPR/micro (node_id 2)
    gpr_odrive_node = Node(
        package='odrive_can',
        executable='odrive_can_node',
        namespace='gpr',
        name='odrive_can_gpr',
        parameters=[{
            'node_id': 2,
            'interface': LaunchConfiguration('can_interface')
        }],
        output='screen'
    )

    # Differential Drive Controller
    # NOTE: GPR (third motor) control is DISABLED here - handled by gpr_scan_controller instead
    diff_drive_controller = Node(
        package='pilot_control',
        executable='diff_drive_controller',
        name='diff_drive_controller',
        output='screen',
        parameters=[{
            'wheel_radius': LaunchConfiguration('wheel_radius'),
            'wheel_base': LaunchConfiguration('wheel_base'),
            'can_interface': LaunchConfiguration('can_interface'),
            'velocity_multiplier': LaunchConfiguration('velocity_multiplier'),
            'turn_speed_multiplier': LaunchConfiguration('turn_speed_multiplier'),
            # Avoid publishing on the same corrected topic as the Python tilt corrector
            'corrected_odom_topic': '/Odometry_tilt_corrected_diff_cpp'
            # GPR CONTROL DISABLED - controlled by gpr_scan_controller instead
            # 'invert_third': True  # COMMENTED OUT - no GPR control from diff_drive_controller
        }]
    )

    # Foxglove Bridge - Maximum buffer settings
    foxglove_bridge = Node(
        package='foxglove_bridge',
        executable='foxglove_bridge',
        name='foxglove_bridge',
        output='screen',
        parameters=[{
            'port': 8765,
            'address': '0.0.0.0',
            'max_q_size': 5000,  # Maximum buffer size
            'num_threads': 16,    # Maximum thread count
            'send_buffer_limit': 100000000,  # Increase send buffer to 100MB
            'capabilities': ['clientPublish', 'connectionGraph', 'parameters', 'parametersSubscribe', 'services', 'subscribe', 'advertise', 'unadvertise', 'getParameters', 'setParameters', 'subscribeParameterUpdates', 'messageDefinitions', 'fetchAsset', 'unsubscribe', 'subscribeConnectionGraph']
        }]
    )

    # Livox ROS Driver (MID360) - Reduced frequency
    livox_driver = Node(
        package='livox_ros_driver2',
        executable='livox_ros_driver2_node',
        prefix='taskset -c 1',  # Dedicated core for LiDAR driver
        name='livox_lidar_publisher',
        output='screen',
        parameters=[{
            'xfer_format': 1,
            'multi_topic': 0,
            'data_src': 0,
            'publish_freq': 10.0,  # Reduced from 10Hz to 3Hz to reduce data load
            'output_data_type': 0,
            'frame_id': 'livox_frame',
            'lvx_file_path': '/home/robot/livox_test.lvx',
            'user_config_path': PathJoinSubstitution([
                FindPackageShare('livox_ros_driver2'), 'config', 'MID360_config.json'
            ])
        }]
    )

    # Fast-LIO2 Node (single-threaded SLAM, needs one fast core)
    fast_lio_node = Node(
        package='fast_lio',
        executable='fastlio_mapping',
        prefix='taskset -c 0',  # Dedicated core 0 for Fast-LIO2 (single-threaded)
        parameters=[PathJoinSubstitution([
            FindPackageShare('pilot_control'), 'config', 'fastlio_mid360.yaml'
        ]), {
            'use_sim_time': False
        }],
        output='screen'
    )

    # Static Transform Publishers for Tilted LiDAR Setup
    # Transform from body to foot (corrects the 15-degree tilt)
    body_to_foot_transform = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='body_to_foot_transform',
        arguments=['0.0', '0.0', '0.0', '0.0', '-0.2618', '0.0', 'body', 'foot'],
        output='screen'
    )
    
    # Transform from camera_init to foot_init (corrects the global frame for visualization)
    camera_init_to_foot_init_transform = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='camera_init_to_foot_init_transform',
        arguments=['0.0','0.0','0.0','0.0','-0.2618','0.0', 'camera_init', 'foot_init'],
        output='screen'
    )

    # Raw Map Saver - Save final accumulated map on-demand (press M key in teleop)
    raw_map_saver = Node(
        package='pilot_control',
        executable='raw_map_saver',
        name='raw_map_saver',
        output='screen',
        parameters=[{
            'input_topic': '/Laser_map',
            'save_directory': '/tmp/robot_maps',  # Fallback until /dc/start sets section folder
            'auto_save_enabled': False,  # Disabled - save only when M key pressed
            'auto_save_interval_sec': 30.0,
            'apply_tilt_correction': True,  # Apply tilt correction when saving
            'calibration_file': tilt_calibration_file,  # Load from config folder
            'lidar_pitch_deg': 15.0,  # Fallback if calibration file not found
            'save_raw_backup': False,  # Set to True to keep uncorrected map as backup
            'save_format': 'compressed'  # 'compressed' (50% smaller, best for wireless transfer), 'binary' (fast), 'ascii' (debug)
        }]
    )

    # PCD Processor - REMOVED (not needed - using raw maps only)

    # Shutdown Service Node (for remote shutdown)
    shutdown_service_node = Node(
        package='pilot_control',
        executable='shutdown_service',
        name='shutdown_service',
        output='screen'
    )

    # GPS Driver (u-blox ZED-F9P via USB)
    gps_driver_node = Node(
        package='pilot_control',
        executable='gps_driver',
        name='gps_driver',
        output='screen',
        parameters=[{
            'device': '/dev/gps',  # Uses udev symlink (fallback: /dev/ttyACM0)
            'baud_rate': 38400,
            'frame_id': 'gps_link',
            # Quality gating thresholds (for /gps/fix output)
            'hacc_max_m': 5.0,           # Max horizontal accuracy (meters)
            'min_sats': 8,               # Min satellites for valid fix
            'pdop_max': 4.0,             # Max position DOP
            'require_3d_fix': True,      # Require 3D fix (fixType >= 3)
            'require_gnss_fix_ok': True, # Require gnssFixOK flag
            # Receiver configuration
            'configure_receiver': True,
            'rate_hz': 5,                # 5Hz update rate
            'dynamic_model': 3,          # 3 = Pedestrian (best for slow robot ~0.5 m/s)
        }]
    )

    # GPR Serial Bridge (Arduino connector)
    gpr_serial_bridge_node = Node(
        package='pilot_control',
        executable='gpr_serial_bridge.py',
        name='gpr_serial_bridge',
        output='screen',
        parameters=[{
            'serial_port': '/dev/arduino',  # stable udev symlink (see config/99-arduino.rules)
            'baud_rate': 9600
        }]
    )

    # GPR Scan Controller - EXCLUSIVE GPR motor control + synchronized scan + logging + rosbag recording
    # This is the ONLY node that controls the GPR motor (diff_drive_controller GPR control is disabled)
    # Also handles rosbag recording to save resources (no separate Python process needed)
    gpr_scan_controller_node = Node(
        package='pilot_control',
        executable='gpr_scan_controller.py',
        name='gpr_scan_controller',
        output='screen',
        parameters=[{
            'gpr_wheel_radius': 0.03,           # 60mm diameter virtual wheel
            'gpr_gear_ratio': 1.0,               # Direct drive
            'velocity_multiplier': LaunchConfiguration('velocity_multiplier'),
            'gpr_scan_velocity_mps': 0.5,        # 0.5 m/s scanning speed
            'invert_third': True,                # GPR motor direction inversion
            'fastlio_odom_topic': '/Odometry_tilt_corrected_diff',  # Use tilt-corrected odometry
            'log_frequency_hz': 50.0,            # 50 Hz logging
            'log_directory': '/R_DATA/gpr_scans',  # Fallback until /dc/start sets section
            'gpr_scan_data_directory': '',  # Set by data_collection_coordinator on /dc/start
            'rosbag_topics': [
                '/Odometry',  # Raw Fast-LIO odometry
                '/Odometry_tilt_corrected_diff',  # Tilt-corrected odometry from diff_drive_controller
                '/cmd_vel',
                '/left/controller_status',
                '/right/controller_status',
                '/gpr/controller_status',
                '/path',
                # '/projected_map',  # 2D occupancy grid from octomap
                '/tf',
                '/tf_static',
                '/livox/imu'
            ]
        }]
    )

    # Laser Map Rotator - tilt correction for occupancy grid
    laser_map_rotator_node = Node(
        package='pilot_control',
        executable='laser_map_rotator',
        name='laser_map_rotator',
        output='screen',
        parameters=[{
            'input_topic': '/Laser_map',
            'output_topic': '/Laser_map_rotated',
            # 'pitch_rad': 0.2617993878,  # 15 degrees
            'output_frame': 'foot_init'
        }]
    )

    # OctoMap Server – builds 3-D occupancy map from rotated cloud
    octomap_server_node = Node(
        package='octomap_server',
        executable='octomap_server_node',
        name='octomap_server',
        output='screen',
        remappings=[('cloud_in', '/Laser_map_rotated')],
        parameters=[
            PathJoinSubstitution([
                FindPackageShare('pilot_control'), 'config', 'octo_occu.yaml'
            ])
        ]
    )

    # Accel MPC Autonomous Controller - drop-in replacement with accel-based MPC
    mpc_controller_node = Node(
        package='pilot_control',
        executable='mpc_accel_autonomous_controller.py',
        name='mpc_accel_autonomous_controller',
        output='screen',
        parameters=[{
            # Robot kinematics
            'wheel_radius': LaunchConfiguration('wheel_radius'),
            'wheel_base': LaunchConfiguration('wheel_base'),
            'gear_ratio': 1.0,
            'invert_left': False,
            'invert_right': True,

            # Control parameters
            'control_frequency': 10.0,          # Hz
            'max_linear_velocity': 0.4,         # m/s
            'max_angular_velocity': 2.0,        # rad/s

            # MPC parameters (Accel controller)
            'mpc_horizon': 50,
            'mpc_dt': 0.1,
            'mpc_Q_xe':25.0, #625 - 0.4m/s
            'mpc_Q_ye': 10.0, #625 - 4cm
            'mpc_Q_yaw':100.0, #131 - 5deg, 625 - 2.29deg, 
            'mpc_R_delta_v': 0.00001, #
            'mpc_R_delta_omega': 0.00001,
            'mpc_weight_increase_xe': 0.20,
            'mpc_weight_increase_ye': 0.20,
            'mpc_weight_increase_yaw': 0.20,

            # Slip/waypoint parameters (accepted for compatibility; slip unused)
            'slip_history_length': 100,
            'slip_estimation_window': 1.0,
            'lookahead_distance': 0.5,
            'target_reached_threshold': 0.01,

            # Topic names (match existing robot wiring)
            'odometry_topic': '/Odometry_tilt_corrected_diff',
            'left_control_topic': '/left/control_message',
            'right_control_topic': '/right/control_message',
            'left_encoder_topic': '/left/controller_status',
            'right_encoder_topic': '/right/controller_status',

            # Solver debug
            'solver_debug_enabled': False,
        }]
    )

    # Auto-start data collection after unified_data_collector is ready
    # start_recording = ExecuteProcess(
    #     cmd=['ros2', 'service', 'call', '/video_record_set', 'std_srvs/srv/SetBool', '{data: true}'],
    #     output='screen'
    # )

    # Data Collection Coordinator - central control for pause/end/delete operations
    data_collection_coordinator_node = Node(
        package='pilot_control',
        executable='data_collection_coordinator.py',
        name='data_collection_coordinator',
        output='screen',
        parameters=[{
            'section_folder': '',  # Created dynamically on /dc/start
            'day_folder': folder_paths['day_folder'],
        }]
    )

    return LaunchDescription([
        # Launch arguments
        declare_wheel_radius_arg,
        declare_wheel_base_arg,
        declare_can_interface_arg,
        declare_can_bitrate_arg,
        declare_velocity_multiplier_arg,
        declare_turn_speed_multiplier_arg,
        declare_base_data_directory_arg,
        
        # Zenoh bridge DDS (must start first for Microhard communication)
        zenoh_bridge,
        
        # CAN setup (with delay to ensure Zenoh and CAN are ready)
        TimerAction(
            period=2.0,
            actions=[can_setup]
        ),
        
        # Robot and mapping components (with delay after CAN setup)
        TimerAction(
            period=3.0,
            actions=[
                left_odrive_node,
                right_odrive_node,
                gpr_odrive_node,
                diff_drive_controller,
                mpc_controller_node,
                livox_driver,  # Core 1 (dedicated)
                fast_lio_node,  # Core 0 (dedicated, single-threaded SLAM)
                # laser_map_rotator_node,
                body_to_foot_transform,
                camera_init_to_foot_init_transform,
                odom_tilt_corrector_node,
                raw_map_saver,  # Enabled - saves final accumulated map (press M)
                # pcd_processor_node - REMOVED (not needed - using raw maps only)
                # octomap_server_node,  # Enabled - generates 2D projected map
                shutdown_service_node,
                unified_data_collector_node, # taskset -c 4,6
                gps_driver_node,  # GPS receiver (u-blox ZED-F9P)
                
                gpr_serial_bridge_node,
                gpr_scan_controller_node, # taskset -c 4,6 (includes rosbag recording)
                data_collection_coordinator_node,  # Central coordinator for pause/end/delete
            ]
        ),
        
        # Auto-start data collection (with delay to ensure unified_data_collector is ready)
        # TimerAction(
        #     period=8.0,
        #     actions=[start_recording]
        # ),
    ]) 